/**
 * @swagger
 * components:
 *   schemas:
 *     Invitation:
 *       type: object
 *       required:
 *         - eventId
 *         - email
 *       properties:
 *         id:
 *           type: string
 *           description: ID autogenerated by MongoDB
 *         eventId:
 *           type: string
 *           description: Event ID
 *         email:
 *           type: string
 *           description: Mail of the invited user
 *         status:
 *           type: string
 *           enum: [pending, accepted, declined]
 *           description: Status of the invitation
 *         sentAt:
 *           type: string
 *           format: date-time
 *           description: Date and time when the invitation was sent
 *       example:
 *         id: "60f7f8f8f8f8f8f8f8f8f8f8"
 *         eventId: "123456"
 *         email: "example@mail.com"
 *         status: "pending"
 *         sentAt: "2023-02-10T12:00:00Z"
 */

/**
 * @swagger
 * /invitations:
 *   get:
 *     summary: Get all invitations
 *     tags: [Invitations]
 *     responses:
 *       200:
 *         description: List of invitations
 */


import express from 'express';
import { createInvitation, getInvitations, updateInvitation, deleteInvitation } from '../controllers/invitationController.js';

const router = express.Router();

router.post('/', createInvitation);
router.get('/', getInvitations);
router.put('/:id', updateInvitation);
router.delete('/:id', deleteInvitation);

export default router;
