openapi: 3.0.0
info:
  title: Rooms Delete Service API
  description: API to delete room records
  version: 1.0.0
servers:
  - url: http://localhost:4094
    description: Local server
paths:
  /rooms/{id}:
    delete:
      summary: Delete a room
      description: Deletes a room by its ID.
      operationId: deleteRoom
      tags:
        - Rooms
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Room deleted successfully
        "404":
          description: Room not found

