version: '3.8'

services:
  rooms-read-service:
    build:
      context: ./rooms-read-service
    ports:
      - "4092:4092"
    environment:
      - MONGO_URI=mongodb://mongo:27017/rooms_db
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
