name: Deploy Invitations Service

on:
  push:
    branches:
      - main
    paths:
      - 'invitations-service/**'
      - '.github/workflows/invitations-service.yml'  # Adding two paths

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          cd invitations-service
          docker build -t esedgarcia/invitations-service:latest .
          docker push esedgarcia/invitations-service:latest

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            # Dowload last image
            docker pull esedgarcia/invitations-service:latest

            # Detener y eliminar el contenedor si ya está corriendo
            docker stop invitations-service || true
            docker rm invitations-service || true

            # Ejecutar el nuevo contenedor con autorestart
            docker run -d -p 4081:4081 --restart unless-stopped --env MONGO_URI=${{ secrets.MONGO_URI }} esedgarcia/invitations-service
