name: Deploy Invitations Service

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/invitations-service.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          cd invitations-service
          docker build -t esedgarcia/invitations-service:latest .
          docker push esedgarcia/invitations-service:latest

      - name: Deploy to EC2 - Pull latest image
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            # Descargar la última imagen
            docker pull esedgarcia/invitations-service:latest

      - name: Deploy to EC2 - Stop and remove existing container
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            # Detener y eliminar el contenedor si ya está corriendo
            if docker ps -a --format '{{.Names}}' | grep -q '^invitations-service$'; then
              docker stop invitations-service || true
              docker rm invitations-service || true
            fi

      - name: Deploy to EC2 - Free port 4081
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            # Liberar el puerto 4081 si está en uso
            if sudo lsof -i :4081; then
              echo "El puerto 4081 está en uso. Deteniendo el proceso..."
              sudo kill -9 $(sudo lsof -t -i :4081)
            fi

      - name: Deploy to EC2 - Run new container
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            # Ejecutar el nuevo contenedor con autorestart
            docker run -d --restart unless-stopped -p 4081:4081 \
              --env MONGO_URI=${{ secrets.MONGO_URI }} \
              --name invitations-service esedgarcia/invitations-service:latest