name: Deploy Payment Service

on:
  push:
    branches:
      - main
    paths:
      - 'payment-service/**'
      - '.github/workflows/payment-service.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t esedgarcia/payment-service:latest ./payment-service
          docker push esedgarcia/payment-service:latest

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST_PS }}
          username: ec2-user
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            # Descargar la última imagen desde Docker Hub
            docker pull esedgarcia/payment-service:latest

            # Detener y eliminar el contenedor si ya está corriendo
            docker stop payment-service || true
            docker rm payment-service || true

            # Ejecutar el nuevo contenedor con nombre fijo
            docker run -d --name payment-service -p 4083:4083 --restart unless-stopped \
              -e MONGO_URI_P=${{ secrets.MONGO_URI }} \
              esedgarcia/payment-service:latest


