name: Deploy Payment Service

on:
  push:
    branches:
      - main
    paths:
      - 'payment-service/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          cd payment-service
          docker build -t esedgarcia/payment-service:latest .
          docker push esedgarcia/payment-service:latest

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            # Descargar la última imagen
            docker pull esedgarcia/payment-service:latest

            # Detener y eliminar el contenedor si ya está corriendo
            docker stop payment-service || true
            docker rm payment-service || true

            # Ejecutar el nuevo contenedor con autorestart
            docker run -d -p 4081:4081 --restart unless-stopped --env MONGO_URI=${{ secrets.MONGO_URI }} esedgarcia/payment-service
